# Site settings
title: bbangjo's blog
url: "https://bgeunjo.github.io/"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: >
  Hello World. I'm bbangjo.

# Your information
email: airmancho@korea.ac.kr
author: Byeonggeun Jo
avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: Working at Corca AI. Studying at Korea University. ðŸ˜„
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  Email: "mailto:your_email@example.com"
  GitHub: "https://github.com/bgeunjo"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or å¤šè¯´)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
