# Site settings

author: bbang_jo
email: airmancho@korea.ac.kr
twitter_username: bgeunjo
github_username:  bgeunjo
#googleplus_username: nop

head-title: bbang_bbang
title: bbang_Jo Practice Range

baseurl: ""    # the subpath of your site, "/blog"
url: "https://bgeunjo.github.io/"

# footer 
description: "I won't be cocky. Let's keep hustle to be a master ğŸ¤£ -bwfs8dq9d#t+eg54&nr4(md3rwd]9cD"
favo: "Challenge in progress : Translate a article of portswigger"
descrpt: |+
  âœ” Challenge Success : dreamhack 50th ğŸ‘<br>
  ğŸ˜¥ Challenge Failed : dreamhack web all solve (ğŸ“…~2020.10.10)<br>
  ğŸ˜¥ Challenge Failed : dreamhack web all solve (ğŸ“…~2020.10.16) all solve on 2020.10.21 ğŸ‘<br>
  âœ” Challenge Success : dreamhack 30th (ğŸ“…~2020.11.07)
  ğŸ˜¥ Challenge Failed : awarded at CCE 2020<br>




#
# Build settings
#

#exclude: [vendor]

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  highlight: true
  auto_ids:  true

sass:
  style: compressed

permalink: /posts/:categories/:title.html

paginate: 7
#paginate_path: 'page/:num'

gems: [jekyll-paginate, jekyll-last-modified-at, jemoji]


#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "indigo lighten-1"
head-theme-color: "#5c6bc0"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "indigo lighten-1"
footer-button-color: "indigo lighten-2"
footer-link-color: "red-text text-accent-1"

share-button-color: "pink"
share-button-small-color: ""


##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt

